import "./core.test.js";
import "./message-accessibility.test.js";
import "./bst.test.js";
import "./bstcopy.test.js";
import "./bstiterator.test.js";
import "./avl.test.js";
import "./bfs.test.js";
import "./bplustree.test.js";
import "./btree.test.js";
import "./closedhash.test.js";
import "./connectedcomponent.test.js";
import "./detectcycle.test.js";
import "./dfs.test.js";
import "./dijkstraprim.test.js";
import "./doublylinkedlist.test.js";
import "./expressiontree.test.js";
import "./heap.test.js";
import "./heapmax.test.js";
import "./heapsort.test.js";
import "./kruskal.test.js";
import "./linkedlist.test.js";
import "./linkedlistsimple.test.js";
import "./linkedlisttail.test.js";
import "./openhash.test.js";
import "./queuearray.test.js";
import "./queuell.test.js";
import "./radixtree.test.js";
import "./redblack.test.js";
import "./search.test.js";
import "./skiplist.test.js";
import "./splaytree.test.js";
import "./stackarray.test.js";
import "./stackll.test.js";
import "./stringhash.test.js";
import "./toposortdfs.test.js";
import "./treap.test.js";
import "./trie.test.js";

import { run } from "./harness.js";

run();
